server:
  port: 8091
  contextPath: /SpringBootEmail

logging:
  config: classpath:log4j2.xml

spring:
  mail:
    host: smtp.163.com
    username: Mrli_yang@163.com
    # 163邮箱客户端授权码或者登陆密码
    password: ly199109131812
    default-encoding: UTF-8

mail:
  fromMail:
    addr: Mrli_yang@163.com