server:
  port: 8091
  contextPath: /SpringBootEmail

logging:
  config: classpath:log4j2.xml

spring:
  mail:
    host: smtp.163.com
    # 163邮箱
    username: **********
    # 163邮箱客户端授权码或者登陆密码
    password: **********
    default-encoding: UTF-8

mail:
  fromMail:
    addr: **********